export const ACTION_START_RANGING = 'ACTION_START_RANGING';
export const ACTION_STOP_RANGING = 'ACTION_STOP_RANGING';

export const ACTION_BEACON_DID_RANGE = 'ACTION_BEACON_DID_RANGE';
export const ACTION_BEACON_SEARCHING = 'ACTION_BEACON_SEARCHING';
