export const ACTION_GOOGLE_SIGN_IN = 'ACTION_GOOGLE_SIGN_IN';
export const ACTION_GOOGLE_SIGN_IN_ERROR = 'ACTION_GOOGLE_SIGN_IN_ERROR';
export const ACTION_VK_SIGN_IN = 'ACTION_VK_SIGN_IN';
export const ACTION_VK_SIGN_IN_ERROR = 'ACTION_VK_SIGN_IN_ERROR';
export const ACTION_SIMPLE_SIGN_IN = 'ACTION_SIMPLE_SIGN_IN';
export const SIGN_IN = 'SIGN_IN';